name: 'Cloudentity CAC'
description: 'Manage Cloudentity configuration as code'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/action-entrypoint.sh'
outputs:
  result:
    description: 'Result of the cac command'