logging:
  level: info
  format: text
client:
  issuer_url: https://postmance.eu.authz.cloudentity.io/postmance/system
  client_id: fb346c287c4d4e378cbae39aa0c3fe52
  client_secret: invalid_secret
storage:
  dir_path: "/tmp/e2e-data"

profiles:
  stage:
    client:
      issuer_url: https://janus.eu.authz.cloudentity.io/janus/system
      client_id: fb346c287c4d4e378cbae39aa0cxxxxx
      client_secret: invalid_secret
    storage:
      dir_path: "/tmp/other"
