name: test action
on:
  push:
    branches:
      - master
      - dev
  pull_request:

permissions:
  contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: ./
          id: cac
          with:
            args: --help
        - run: echo -e "${{ steps.cac.outputs.result }}"
          name: print action output
    negative-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: ./
            id: cac
            with:
              args: pull --invalid
            continue-on-error: true
          - if: steps.cac.outcome == 'success'
            name: fail on cac success
            run: exit 1
          - if: steps.cac.outcome == 'failure'
            run: echo "cac failed as expected"
